<?php
// File : indonesian/localized.cmds.php (23.08.2009 - rev.1)
// Translation by Hendriyo <hendriyo@gmail.com>
// Do not use ' but use ’ instead (utf-8 edit bug)

// You can use more than one word (synonyms, abbreviations) as commands in your language. Multiple words must be separated by commas, without spaces! You have the original English strings/commands as examples below (no need to add the English words here)
# Example: define("L_CMD_AWAY", "plec,brb,revin");

define("L_CMD_ANNOUNCE", "peng,pengumuman,meng,mengumumkan"); // announce (send a global announcement in all rooms)
define("L_CMD_AWAY", "pergi"); // away (set as away from pc or back)
define("L_CMD_BAN", "dilarang"); // ban (block an user from joining chat)
define("L_CMD_BOT", "robot"); // bot (start/stop the bot in a room)
define("L_CMD_BUZZ", "dengung"); // buzz (play a buzz/sound alert in the room)
define("L_CMD_CLEAR", "bersihkan"); // clear (clear the messages frame and show only the last 5 posts)
define("L_CMD_DEMOTE", "turun,turunjabatan"); // demote (demote an user to the lower power level - admin->mod->user)
define("L_CMD_DICE", "dadu"); // dice (throw the dice)
define("L_CMD_HELP", "tolong"); // ?,help (open the help popup page)
define("L_CMD_HIGH", "tinggi"); // high (highlight someone's posts)
define("L_CMD_IGNORE", "hiraukan"); // ignore (ignore an user - hide his posts and show the list of ignored people)
define("L_CMD_IMG", "gambar"); // img (post an image in the chat)
define("L_CMD_INVITE", "undang"); // invite (send an invitation to the user to follow you in your room)
define("L_CMD_JOIN", "bergabung"); // join (join an existing room)
define("L_CMD_KICK", "tendang,ulang"); // kick,boot (kick an user from a room)
define("L_CMD_LTR", "kirkan,kirikanan"); // ltr (post a left-to-right text)
define("L_CMD_MATH", ""); //math (post MathJax equations in chat)
define("L_CMD_ME", "saya"); // me (tell the room what you are doing)
define("L_CMD_MR", "sdr"); // mr (same as "me" but with the gender prefix)
define("L_CMD_MSG", "psn,ke"); // msg,to (send a private message)
define("L_CMD_NOTIFY", "berita"); // notify (enable/disable notifications)
define("L_CMD_ORDER", "perintah"); // order (change the posts order to first-on-top or first-on-bottom - not available in IE and FF)
define("L_CMD_PROFILE", "biodata"); // profile (open the personal profile page for editing)
define("L_CMD_PROMOTE", "naik,naikjabatan"); // promote (promote an user to the next power level - user->mod->admin)
define("L_CMD_QUIT", "keluar,dadaa"); // quit,bye,exit (quit a room)
define("L_CMD_RECALL", "memanggil"); // !,recall (recall last sent message in the message box)
define("L_CMD_REFRESH", "proses,ulang"); // refresh,reload (modify/reset the time between browser refreshes/reloads)
define("L_CMD_ROOM", "kamar"); // room (send an announcement/warning to the current room)
define("L_CMD_RTL", "kankir,kanankiri"); // rtl (post a right-to-left text)
define("L_CMD_SAVE", "simpan,ekspor"); // save,export (open the last N posts to be exported)
define("L_CMD_SHOW", "tampilkan,akhir"); // show,last (reset the messages frame to show the last 5 / N posts only)
define("L_CMD_SIZE", "ukuran"); // size (change/reset the size of the font in chat)
define("L_CMD_SORT", "urut"); // sort (sort - ascending the usernames in the lists, alphabetically or by the time they joined chat)
define("L_CMD_TIMESTAMP", "waktu"); // timestamp (show/hide the timestamp in posts and server/worldtime in the status bar)
define("L_CMD_TOPIC", "topik"); // topic (set/change the topic)
define("L_CMD_UTUBE", ""); // tube,utube,youtube (post an youtube video)
define("L_CMD_VIDEO", ""); // vid,video,play (post a video)
define("L_CMD_WISP", "siul,siulan"); //wisp,whisp (send a whisper / private message to an user in a different room)
define("L_CMD_WHOIS", "siapaini,tentang"); // whois,about (shows the profile page of an user) 
?>