<?php
// File : serbian_latin/localized.cmds.php (23.08.2009 - rev.1)
// Original translation by Vedran Vučić <vedran.vucic@gnulinuxcentar.org>
// Do not use ' but use ’ instead (utf-8 edit bug)

// You can use more than one word (synonyms, abbreviations) as commands in your language. Multiple words must be separated by commas, without spaces! You have the original English strings/commands as examples below (no need to add the English words here)
define("L_CMD_ANNOUNCE", "obav,obavestenje,obaveštenje"); // announce (send a global announcement in all rooms)
define("L_CMD_AWAY", "odsutan"); // away (set as away from pc or back)
define("L_CMD_BAN", "blok,blokiranje"); // ban (block an user from joining chat)
define("L_CMD_BOT", ""); // bot (start/stop the bot in a room)
define("L_CMD_BUZZ", ""); // buzz (play a buzz/sound alert in the room)
define("L_CMD_CLEAR", "ocisti,očisti"); // clear (clear the messages frame and show only the last 5 posts)
define("L_CMD_DEMOTE", "opoz,opozovi"); // demote (demote an user to the lower power level - admin->mod->user)
define("L_CMD_DICE", "kocka"); // dice (throw the dice)
define("L_CMD_HELP", "pomoc,pomoć"); // ?,help (open the help popup page)
define("L_CMD_HIGH", "naglasi"); // high (highlight someones posts)
define("L_CMD_IGNORE", "ignor,ignorisi,ignoriši"); // ignore (ignore an user - hide his posts and show the list of ignored people)
define("L_CMD_IMG", "slika"); // img (post an image in the chat)
define("L_CMD_INVITE", "poziv"); // invite (send an invitation to the user to follow you in your room)
define("L_CMD_JOIN", "prik,prikljuci,priključi"); // join (join an existing room)
define("L_CMD_KICK", "izbaci,udalji"); // kick,boot (kick an user from a room)
define("L_CMD_LTR", "lud,lev,leva"); // ltr (post a left-to-right text)
define("L_CMD_ME", "ja"); // me (tell the room what you are doing)
define("L_CMD_MR", "gosp,go"); // mr (same as "me" but with the gender prefix)
define("L_CMD_MSG", "za,poruka"); // msg,to (send a private message)
define("L_CMD_NOTIFY", "napomene"); // notify (enable/disable notifications)
define("L_CMD_ORDER", "redosled"); // order (change the posts order to first-on-top or first-on-bottom - not available in IE and FF)
define("L_CMD_PROFILE", "profil"); // profile (open the personal profile page for editing)
define("L_CMD_PROMOTE", "unap,unapredi"); // promote (promote an user to the next power level - user->mod->admin)
define("L_CMD_QUIT", "cao,ćao,zatvori,izlaz"); // quit,bye,exit (quit a room)
define("L_CMD_RECALL", "ponovi,poruku"); // !,recall (recalls last sent message in the message box)
define("L_CMD_REFRESH", "osvez,osvezavanje,osvežavanje,ponovno,ucita,ucitavanje,učitavanje"); // refresh,reload (modify/reset the time between browser refreshes/reloads)
define("L_CMD_ROOM", "soba"); // room (send an announcement/warning to the current room)
define("L_CMD_RTL", "dul,des,desna"); // rtl (post a right-to-left text)
define("L_CMD_SAVE", "snimi,izvezi"); // save,export (open the last N posts to be exported)
define("L_CMD_SHOW", "pokazi,pokaži,posle,poslednje"); // show,last (reset the messages frame to show the last 5 / N posts only)
define("L_CMD_SIZE", "veli,velicina,veličina"); //size (change/reset the size of the font in chat)
define("L_CMD_SORT", "sortir,sortiranje"); // sort (sort - ascending the usernames in the lists, alphabetically or by the time they joined chat)
define("L_CMD_TIMESTAMP", "oznaka,vremena"); // timestamp (show/hide the timestamp in posts and server/worldtime in the status bar)
define("L_CMD_TOPIC", "tema"); // topic (set/change the topic)
define("L_CMD_WISP", "sapat,šapat,saotanje,šaotanje"); //wisp,whisp (send a whisper / private message to an user in a different room)
define("L_CMD_WHOIS", "ko,koje,korisniku"); // whois,about (shows the profile page of an user) 
?>