:\)	|	smile1.gif
:-\)	|	smile1.gif
:D	|	smile2.gif
:o	|	smile3.gif
:O	|	smile3.gif
:\(	|	smile4.gif
:-\(	|	smile4.gif
;\)	|	smile5.gif
:p	|	smile6.gif
:P	|	smile6.gif
8\)	|	smile7.gif
8-\)	|	smile7.gif
:\[	|	smile8.gif
:-\[	|	smile8.gif
:kill:	|	smile9.gif
:wave	|	smile10.gif
:baby	|	smile11.gif
:nono	|	smile12.gif
:shuks	|	smile13.gif
:blush	|	smile14.gif
:sad	|	smile15.gif
:drool	|	smile16.gif
:nuts	|	smile17.gif
:hardhat	|	smile18.gif
:thum	|	smile19.gif
:foot	|	smile20.gif
:hug	|	smile21.gif
:sneak	|	smile22.gif
:handshake	|	smile23.gif
:kiss	|	smile24.gif
:\*	|	smile24.gif
:-\*	|	smile24.gif
:x	|	smile24.gif
:-x	|	smile24.gif
:heart	|	smile25.gif
:bang	|	smile26.gif
:type	|	smile27.gif
:read	|	smile28.gif
:zzzz	|	smile29.gif
:eat	|	smile30.gif
:angl	|	smile31.gif
:love	|	smile32.gif
:flirt	|	smile33.gif
:rant	|	smile34.gif
:rofl	|	smile35.gif
:idea	|	smile36.gif
:silly	|	smile37.gif
:wow	|	smile38.gif
:clps	|	smile39.gif
:disco	|	smile40.gif
:clap	|	smile41.gif
:yah	|	smile42.gif
:splat	|	smile43.gif
:uch	|	smile44.gif
:cryn	|	smile45.gif
:whoa	|	smile46.gif
:nana	|	smile47.gif
:yea	|	smile48.gif
:drnk	|	smile49.gif
:devil	|	smile50.gif
:cat	|	smile51.gif
:buds	|	smile52.gif
:dead	|	smile53.gif
:hey	|	smile54.gif
:wink	|	smile55.gif
:hahaha	|	smile56.gif
:hy	|	smile57.gif
:mad	|	smile58.gif
:shock	|	smile59.gif
:slap	|	smile60.gif
:bop	|	smile61.gif
:music	|	smile62.gif
:argue	|	smile63.gif
:mischief	|	smile64.gif
:groin	|	smile65.gif
;punch	|	smile66.gif
:drunk	|	smile67.gif
:back	|	smile68.gif

## NOTE: keep at least one blank line above!
## NOTE: format is: "code" + "tab" + "|" + "tab" + "imagefile" + Hit Return