<?php
// File : chinese_traditional/localized.cmds.php (20.03.2010 - rev.2)
// Translation by clouds_music <clouds.music@gmail.com>
// Do not use ' but use ’ instead (utf-8 edit bug)

// You can use more than one word (synonyms, abbreviations) as commands in your language. Multiple words must be separated by commas, without spaces! You have the original English strings/commands as examples below (no need to add the English words here)
define("L_CMD_ANNOUNCE", "公告"); // announce (send a global announcement in all rooms)
define("L_CMD_AWAY", "暫離"); // away (set as away from pc or back)
define("L_CMD_BAN", "封鎖"); // ban (block an user from joining chat)
define("L_CMD_BOT", "機器人"); // bot (start/stop the bot in a room)
define("L_CMD_BUZZ", "嗶聲"); // buzz (play a buzz/sound alert in the room)
define("L_CMD_CLEAR", "清除"); // clear (clear the messages frame and show only the last 5 posts)
define("L_CMD_DEMOTE", "降級"); // demote (demote an user to the lower power level - admin->mod->user)
define("L_CMD_DICE", "骰子"); // dice (throw the dice)
define("L_CMD_HELP", "幫助"); // ?,help (open the help popup page)
define("L_CMD_HIGH", "高亮"); // high (highlight someones posts)
define("L_CMD_IGNORE", "忽略"); // ignore (ignore an user - hide his posts and show the list of ignored people)
define("L_CMD_IMG", "圖片"); // img (post an image in the chat)
define("L_CMD_INVITE", "邀請"); // invite (send an invitation to the user to follow you in your room)
define("L_CMD_JOIN", "登入"); // join (join an existing room)
define("L_CMD_KICK", "踢"); // kick,boot (kick an user from a room)
define("L_CMD_LTR", "左右"); // ltr (post a left-to-right text)
define("L_CMD_ME", "自己"); // me (tell the room what you are doing)
define("L_CMD_MR", "敬稱"); // mr (same as "me" but with the gender prefix)
define("L_CMD_MSG", "悄悄話"); // msg,to (send a private message)
define("L_CMD_NOTIFY", "通知"); // notify (enable/disable notifications)
define("L_CMD_ORDER", "順序"); // order (change the posts order to first-on-top or first-on-bottom - not available in IE and FF)
define("L_CMD_PROFILE", "個人資料"); // profile (open the personal profile page for editing)
define("L_CMD_PROMOTE", "升級"); // promote (promote an user to the next power level - user->mod->admin)
define("L_CMD_QUIT", "離開,退出,再見"); // quit,bye,exit (quit a room)
define("L_CMD_RECALL", "召回"); // !,recall (recalls last sent message in the message box)
define("L_CMD_REFRESH", "更新,刷新"); // refresh,reload (modify/reset the time between browser refreshes/reloads)
define("L_CMD_ROOM", "房間"); // room (send an announcement/warning to the current room)
define("L_CMD_RTL", "右左"); // rtl (post a right-to-left text)
define("L_CMD_SAVE", "保存,導出"); // save,export (open the last N posts to be exported)
define("L_CMD_SHOW", "顯示,最新"); // show,last (reset the messages frame to show the last 5 / N posts only)
define("L_CMD_SIZE", "大小"); //size (change/reset the size of the font in chat)
define("L_CMD_SORT", "排序,升序排序"); // sort (sort - ascending the usernames in the lists, alphabetically or by the time they joined chat)
define("L_CMD_TIMESTAMP", "時間,時間隱藏"); // timestamp (show/hide the timestamp in posts and server/worldtime in the status bar)
define("L_CMD_TOPIC", "話題,更改話題"); // topic (set/change the topic)
define("L_CMD_UTUBE", "視訊"); //tube,utube,youtube (posts an youtube video movie in an embedded Flash player)
define("L_CMD_VIDEO", "視頻,播放"); //vid,video,play (posts a video movie or an audio source in an embedded Flash player)
define("L_CMD_WISP", "密談"); //wisp,whisp (send a whisper / private message to an user in a different room)
define("L_CMD_WHOIS", "誰"); // whois,about (shows the profile page of an user) 
?>