<?php
// File : italian/localized.cmds.php (23.08.2009 - rev.1)
// Translation by Michele Ferro <specialmikius@yahoo.com>
// Do not use ' but use ’ instead (utf-8 edit bug)

// You can use more than one word (synonyms, abbreviations) as commands in your language. Multiple words must be separated by commas, without spaces! You have the original English strings/commands as examples below (no need to add the English words here)
# Example: define("L_CMD_AWAY", "plec,brb,revin");

define("L_CMD_ANNOUNCE", "annuncio,avvertimento"); // announce (send a global announcement in all rooms)
define("L_CMD_AWAY", "assente"); // away (set as away from pc or back)
define("L_CMD_BAN", "blocca"); // ban (block an user from joining chat)
define("L_CMD_BOT", "avvia"); // bot (start/stop the bot in a room)
define("L_CMD_BUZZ", ""); // buzz (play a buzz/sound alert in the room)
define("L_CMD_CLEAR", "cancella"); // clear (clear the messages frame and show only the last 5 posts)
define("L_CMD_DEMOTE", "degrada,riduci"); // demote (demote an user to the lower power level - admin->mod->user)
define("L_CMD_DICE", "dado"); // dice (throw the dice)
define("L_CMD_HELP", "aiuto"); // ?,help (open the help popup page)
define("L_CMD_HIGH", "evidenzia,seleziona"); // high (highlight someone's posts)
define("L_CMD_IGNORE", "ignora"); // ignore (ignore an user - hide his posts and show the list of ignored people)
define("L_CMD_IMG", "imm,immagine"); // img (post an image in the chat)
define("L_CMD_INVITE", "invita"); // invite (send an invitation to the user to follow you in your room)
define("L_CMD_JOIN", "entra"); // join (join an existing room)
define("L_CMD_KICK", "elimina"); // kick,boot (kick an user from a room)
define("L_CMD_LTR", "sad,sin,sinistra "); // ltr (post a left-to-right text)
define("L_CMD_MATH", ""); //math (post MathJax equations in chat)
define("L_CMD_ME", "io"); // me (tell the room what you are doing)
define("L_CMD_MR", "sig"); // mr (same as "me" but with the gender prefix)
define("L_CMD_MSG", "a,mess,invia"); // msg,to (send a private message)
define("L_CMD_NOTIFY", "avvisi,notifiche"); // notify (enable/disable notifications)
define("L_CMD_ORDER", "ordina,mostra"); // order (change the posts order to first-on-top or first-on-bottom - not available in IE and FF)
define("L_CMD_PROFILE", "profilo"); // profile (open the personal profile page for editing)
define("L_CMD_PROMOTE", "promuovi,grado,aumenta"); // promote (promote an user to the next power level - user->mod->admin)
define("L_CMD_QUIT", "esci,lascia"); // quit,bye,exit (quit a room)
define("L_CMD_RECALL", "richiama"); // !,recall (recall last sent message in the message box)
define("L_CMD_REFRESH", "aggiorna,ricarica"); // refresh,reload (modify/reset the time between browser refreshes/reloads)
define("L_CMD_ROOM", "stanza"); // room (send an announcement/warning to the current room)
define("L_CMD_RTL", "das,des,destra"); // rtl (post a right-to-left text)
define("L_CMD_SAVE", "salva,esporta"); // save,export (open the last N posts to be exported)
define("L_CMD_SHOW", "finali,ultimi"); // show,last (reset the messages frame to show the last 5 / N posts only)
define("L_CMD_SIZE", "misura,grandezza"); //size (change/reset the size of the font in chat)
define("L_CMD_SORT", "elenca"); // sort (sort - ascending the usernames in the lists, alphabetically or by the time they joined chat)
define("L_CMD_TIMESTAMP", "ora,tempo"); // timestamp (show/hide the timestamp in posts and server/worldtime in the status bar)
define("L_CMD_TOPIC", "argomento"); // topic (set/change the topic)
define("L_CMD_UTUBE", ""); // tube,utube,youtube (post an youtube video)
define("L_CMD_VIDEO", ""); // vid,video,play (post a video)
define("L_CMD_WISP", "sus,sussurro"); //wisp,whisp (send a whisper / private message to an user in a different room)
define("L_CMD_WHOIS", "chie,chiè"); // whois,about (shows the profile page of an user)
?>