<?php
// File: swedish/localized.cmds.php (23.08.2009 - rev.1)
// Translation by Fimpen Högström <fimpen@relative-work.se>
// Do not use ' but use ’ instead (utf-8 edit bug)

// You can use more than one word (synonyms, abbreviations) as commands in your language. Multiple words must be separated by commas, without spaces! You have the original English strings/commands as examples below (no need to add the English words here)
# Example: define("L_CMD_AWAY", "plec,brb,revin");

define("L_CMD_ANNOUNCE", "kungodande,kungörande"); // announce (send a global announcement in all rooms)
define("L_CMD_AWAY", "ivag,iväg"); // away (set as away from pc or back)
define("L_CMD_BAN", "avstang,avstäng"); // ban (block an user from joining chat)
define("L_CMD_BOT", "robot"); // bot (start/stop the bot in a room)
define("L_CMD_BUZZ", "ljud"); // buzz (play a buzz/sound alert in the room)
define("L_CMD_CLEAR", "rensa"); // clear (clear the messages frame and show only the last 5 posts)
define("L_CMD_DEMOTE", "nergradera"); // demote (demote an user to the lower power level - admin->mod->user)
define("L_CMD_DICE", "tarningsspel,tärningsspel"); // dice (throw the dice)
define("L_CMD_HELP", "hjalp,hjälp"); // ?,help (open the help popup page)
define("L_CMD_HIGH", "markera"); // high (highlight someone's posts)
define("L_CMD_IGNORE", "ignorera"); // ignore (ignore an user - hide his posts and show the list of ignored people)
define("L_CMD_IMG", "bild"); // img (post an image in the chat)
define("L_CMD_INVITE", "inventera,bjud"); // invite (send an invitation to the user to follow you in your room)
define("L_CMD_JOIN", "anslut"); // join (join an existing room)
define("L_CMD_KICK", "uteslut,kicka"); // kick,boot (kick an user from a room)
define("L_CMD_LTR", "vth,vanster,vänster"); // ltr (post a left-to-right text)
define("L_CMD_MATH", ""); //math (post MathJax equations in chat)
define("L_CMD_ME", "mig"); // me (tell the room what you are doing)
define("L_CMD_MR", "herr"); // mr (same as "me" but with the gender prefix)
define("L_CMD_MSG", "skicka,till"); // msg,to (send a private message)
define("L_CMD_NOTIFY", "avisera,varsko"); // notify (enable/disable notifications)
define("L_CMD_ORDER", "ordning"); // order (change the posts order to first-on-top or first-on-bottom - not available in IE and FF)
define("L_CMD_PROFILE", "profil"); // profile (open the personal profile page for editing)
define("L_CMD_PROMOTE", "uppgradera"); // promote (promote an user to the next power level - user->mod->admin)
define("L_CMD_QUIT", "stang,stäng,stängning,nara,nära,lamna,lämna"); // quit,bye,exit (quit a room)
define("L_CMD_RECALL", "minns,historia"); // !,recall (recall last sent message in the message box)
define("L_CMD_REFRESH", "uppdatera "); // refresh,reload (modify/reset the time between browser refreshes/reloads)
define("L_CMD_ROOM", "rum"); // room (send an announcement/warning to the current room)
define("L_CMD_RTL", "htv,hoger,höger"); // rtl (post a right-to-left text)
define("L_CMD_SAVE", "spara,exportera"); // save,export (open the last N posts to be exported)
define("L_CMD_SHOW", "visa,senaste"); // show,last (reset the messages frame to show the last 5 / N posts only)
define("L_CMD_SIZE", "storlek"); //size (change/reset the size of the font in chat)
define("L_CMD_SORT", "sortera"); // sort (sort - ascending the usernames in the lists, alphabetically or by the time they joined chat)
define("L_CMD_TIMESTAMP", "tidskod,tid"); // timestamp (show/hide the timestamp in posts and server/worldtime in the status bar)
define("L_CMD_TOPIC", "amne,ämne"); // topic (set/change the topic)
define("L_CMD_UTUBE", ""); // tube,utube,youtube (post an youtube video)
define("L_CMD_VIDEO", ""); // vid,video,play (post a video)
define("L_CMD_WISP", "viska"); //wisp,whisp (send a whisper / private message to an user in a different room)
define("L_CMD_WHOIS", "om,somar,somär"); // whois,about (shows the profile page of an user) 
?>