<?php
// File : vietnamese/localized.cmds.php (23.08.2009 - rev.1)
// Translation by Marshall <hellomarshall_lookatme@yahoo.com.vn>
// Do not use ' but use ’ instead (utf-8 edit bug)

// You can use more than one word (synonyms, abbreviations) as commands in your language. Multiple words must be separated by commas, without spaces! You have the original English strings/commands as examples below (no need to add the English words here)
define("L_CMD_ANNOUNCE", "congbo,côngbố"); // announce (send a global announcement in all rooms)
define("L_CMD_AWAY", "cahcxa,cáchxa,rakhoi,rakhỏi"); // away (set as away from pc or back)
define("L_CMD_BAN", "cấm"); // ban (block an user from joining chat)
define("L_CMD_BOT", ""); // bot (start/stop the bot in a room)
define("L_CMD_BUZZ", "rung"); // buzz (play a buzz/sound alert in the room)
define("L_CMD_CLEAR", "lamsach,làmsạch"); // clear (clear the messages frame and show only the last 5 posts)
define("L_CMD_DEMOTE", "hachuc,hạchức,giangchuc,giángchức"); // demote (demote an user to the lower power level - admin->mod->user)
define("L_CMD_DICE", "xucxac,xúcxắc"); // dice (throw the dice)
define("L_CMD_HELP", "trogiup,trợgiúp"); // ?,help (open the help popup page)
define("L_CMD_HIGH", "lamnoi,làmnổi"); // high (highlight someones posts)
define("L_CMD_IGNORE", "lodi"); // ignore (ignore an user - hide his posts and show the list of ignored people)
define("L_CMD_IMG", "anh,ảnh"); // img (post an image in the chat)
define("L_CMD_INVITE", "moi,mời,loimoi,lờimời"); // invite (send an invitation to the user to follow you in your room)
define("L_CMD_JOIN", "gianhap,gianhập"); // join (join an existing room)
define("L_CMD_KICK", "da,đá,rangoai"); // kick,boot (kick an user from a room)
define("L_CMD_LTR", "tsp,traisangphai,tráisangphải"); // ltr (post a left-to-right text)
define("L_CMD_ME", "toi,tôi"); // me (tell the room what you are doing)
define("L_CMD_MR", "ong,ông"); // mr (same as "me" but with the gender prefix)
define("L_CMD_MSG", "tinnhan,tinnhắn"); // msg,to (send a private message)
define("L_CMD_NOTIFY", "thongbao,thôngbáo"); // notify (enable/disable notifications)
define("L_CMD_ORDER", "menhlenh,mệnhlệnh"); // order (change the posts order to first-on-top or first-on-bottom - not available in IE and FF)
define("L_CMD_PROFILE", "tieusu"); // profile (open the personal profile page for editing)
define("L_CMD_PROMOTE", "daymanh,đẩymạnh"); // promote (promote an user to the next power level - user->mod->admin)
define("L_CMD_QUIT", "dong,đóng,tambiet,tạmbiệt,thoat,thoát"); // quit,bye,exit (quit a room)
define("L_CMD_RECALL", "nhanlai,nhắnlại"); // !,recall (recalls last sent message in the message box)
define("L_CMD_REFRESH", "tailai,lamtuoi,tảilại,làmtươi"); // refresh,reload (modify/reset the time between browser refreshes/reloads)
define("L_CMD_ROOM", "phong,phòng"); // room (send an announcement/warning to the current room)
define("L_CMD_RTL", "pst,phaisangtrai,phảisangtrái"); // rtl (post a right-to-left text)
define("L_CMD_SAVE", "giulai,dayra,giữlại,đẩyra"); // save,export (open the last N posts to be exported)
define("L_CMD_SHOW", "hienra,cuoicung,hiệnra,cuốicùng"); // show,last (reset the messages frame to show the last 5 / N posts only)
define("L_CMD_SIZE", "kichthuoc,kíchthước"); //size (change/reset the size of the font in chat)
define("L_CMD_SORT", "loai,loại"); // sort (sort - ascending the usernames in the lists, alphabetically or by the time they joined chat)
define("L_CMD_TIMESTAMP", "lichtrinh,lịchtrình"); // timestamp (show/hide the timestamp in posts and server/worldtime in the status bar)
define("L_CMD_TOPIC", "detai,đềtài"); // topic (set/change the topic)
define("L_CMD_WISP", "mo,mớ"); //wisp,whisp (send a whisper / private message to an user in a different room)
define("L_CMD_WHOIS", "tracuu,tracứu"); // whois,about (shows the profile page of an user) 
?>