<?php
// File : japanese/localized.cmds.php (20.03.2010 - rev.2)
// Translation by Dendeke <konchakka211@yahoo.co.jp>
// Do not use ' but use ’ instead (utf-8 edit bug)

// You can use more than one word (synonyms, abbreviations) as commands in your language. Multiple words must be separated by commas, without spaces! You have the original English strings/commands as examples below (no need to add the English words here)
define("L_CMD_ANNOUNCE", "お知らせ"); // announce (send a global announcement in all rooms)
define("L_CMD_AWAY", "離席"); // away (set as away from pc or back)
define("L_CMD_BAN", "追放"); // ban (block an user from joining chat)
define("L_CMD_BOT", "ロボット"); // bot (start/stop the bot in a room)
define("L_CMD_BUZZ", "ビープ"); // buzz (play a buzz/sound alert in the room)
define("L_CMD_CLEAR", "掃除"); // clear (clear the messages frame and show only the last 5 posts)
define("L_CMD_DEMOTE", "剥奪"); // demote (demote an user to the lower power level - admin->mod->user)
define("L_CMD_DICE", "ダイス"); // dice (throw the dice)
define("L_CMD_HELP", "ヘルプ"); // ?,help (open the help popup page)
define("L_CMD_HIGH", "ハイライト"); // high (highlight someones posts)
define("L_CMD_IGNORE", "無視"); // ignore (ignore an user - hide his posts and show the list of ignored people)
define("L_CMD_IMG", "画像"); // img (post an image in the chat)
define("L_CMD_INVITE", "招待"); // invite (send an invitation to the user to follow you in your room)
define("L_CMD_JOIN", "参加"); // join (join an existing room)
define("L_CMD_KICK", "キック"); // kick,boot (kick an user from a room)
define("L_CMD_LTR", "左右"); // ltr (post a left-to-right text)
define("L_CMD_MATH", ""); //math (post MathJax equations in chat)
define("L_CMD_ME", "自分"); // me (tell the room what you are doing)
define("L_CMD_MR", "敬称"); // mr (same as "me" but with the gender prefix)
define("L_CMD_MSG", "耳打ち"); // msg,to (send a private message)
define("L_CMD_NOTIFY", "告知"); // notify (enable/disable notifications)
define("L_CMD_ORDER", "順序"); // order (change the posts order to first-on-top or first-on-bottom - not available in IE and FF)
define("L_CMD_PROFILE", "プロファイル"); // profile (open the personal profile page for editing)
define("L_CMD_PROMOTE", "付与"); // promote (promote an user to the next power level - user->mod->admin)
define("L_CMD_QUIT", "退室,終了,バイバイ"); // quit,bye,exit (quit a room)
define("L_CMD_RECALL", "呼び出し"); // !,recall (recalls last sent message in the message box)
define("L_CMD_REFRESH", "更新,リフレッシュ"); // refresh,reload (modify/reset the time between browser refreshes/reloads)
define("L_CMD_ROOM", "部屋"); // room (send an announcement/warning to the current room)
define("L_CMD_RTL", "右左"); // rtl (post a right-to-left text)
define("L_CMD_SAVE", "保存,エキスポート,排出,書き出し"); // save,export (open the last N posts to be exported)
define("L_CMD_SHOW", "表示,最新"); // show,last (reset the messages frame to show the last 5 / N posts only)
define("L_CMD_SIZE", "サイズ"); //size (change/reset the size of the font in chat)
define("L_CMD_SORT", "ソート,並び替え"); // sort (sort - ascending the usernames in the lists, alphabetically or by the time they joined chat)
define("L_CMD_TIMESTAMP", "時刻,日時"); // timestamp (show/hide the timestamp in posts and server/worldtime in the status bar)
define("L_CMD_TOPIC", "トピック,題材"); // topic (set/change the topic)
define("L_CMD_UTUBE", "ユーチューブ,チューブ"); //tube,utube,youtube (posts an youtube video movie in an embedded Flash player)
define("L_CMD_VIDEO", "ビデオ"); //vid,video,play (posts a video movie or an audio source in an embedded Flash player)
define("L_CMD_WISP", "内緒"); //wisp,whisp (send a whisper / private message to an user in a different room)
define("L_CMD_WHOIS", "誰"); // whois,about (shows the profile page of an user) 
?>