<?php
// File : brazilian_portuguese/localized.cmds.php (09.01.2012 - rev.3)
// Translation by Marco Gelli Marchese <mvmcgm@gmail.com>
// Do not use ' but use ’ instead (utf-8 edit bug)

// You can use more than one word (synonyms, abbreviations) as commands in your language. Multiple words must be separated by commas, without spaces! You have the original English strings/commands as examples below (no need to add the English words here)
# Example: define("L_CMD_AWAY", "plec,brb,revin");

define("L_CMD_ANNOUNCE", "aviso,anunciar,anúnciar,anuncio,anúncio"); // announce (send a global announcement in all rooms)
define("L_CMD_AWAY", "aus,ausente"); // away (set as away from pc or back)
define("L_CMD_BAN", "banir,bloq"); // ban (block an user from joining chat)
define("L_CMD_BOT", "robo"); // bot (start/stop the bot in a room)
define("L_CMD_BUZZ", "som,buzina"); // buzz (play a buzz/sound alert in the room)
define("L_CMD_CLEAR", "lim,limpar"); // clear (clear the messages frame and show only the last 5 posts)
define("L_CMD_DEMOTE", "reb,rebaixar"); // demote (demote an user to the lower power level - admin->mod->user)
define("L_CMD_DICE", "dado"); // dice (throw the dice)
define("L_CMD_HELP", "ajuda"); // ?,help (open the help popup page)
define("L_CMD_HIGH", "real,realcar,realçar"); // high (highlight someone's posts)
define("L_CMD_IGNORE", "ignora,ignorar"); // ignore (ignore an user - hide his posts and show the list of ignored people)
define("L_CMD_IMG", "foto,imagem"); // img (post an image in the chat)
define("L_CMD_INVITE", "convite"); // invite (send an invitation to the user to follow you in your room)
define("L_CMD_JOIN", "entra"); // join (join an existing room)
define("L_CMD_KICK", "chutar"); // kick,boot (kick an user from a room)
define("L_CMD_LTR", "epd"); // ltr (post a left-to-right text)
define("L_CMD_MATH", "mat"); // math (post MathJax equations in chat)
define("L_CMD_ME", "eu"); // me (tell the room what you are doing)
define("L_CMD_MR", "eum"); // mr (same as "me" but with the gender prefix)
define("L_CMD_MSG", "para"); // msg,to (send a private message)
define("L_CMD_NOTIFY", "notificar"); // notify (enable/disable notifications)
define("L_CMD_ORDER", "ord,ordem"); // order (change the posts order to first-on-top or first-on-bottom - not available in IE and FF)
define("L_CMD_PROFILE", "perfil"); // profile (open the personal profile page for editing)
define("L_CMD_PROMOTE", "prom,promover"); // promote (promote an user to the next power level - user->mod->admin)
define("L_CMD_QUIT", "sair,tchau"); // quit,bye,exit (quit a room)
define("L_CMD_RECALL", "rec,recordar"); // !,recall (recall last sent message in the message box)
define("L_CMD_REFRESH", "atu,atualizar"); // refresh,reload (modify/reset the time between browser refreshes/reloads)
define("L_CMD_ROOM", "sala"); // room (send an announcement/warning to the current room)
define("L_CMD_RTL", "dpe"); // rtl (post a right-to-left text)
define("L_CMD_SAVE", "salv,salvar,exportar"); // save,export (open the last N posts to be exported)
define("L_CMD_SHOW", "most,mostrar,ultimo"); // show,last (reset the messages frame to show the last 5 / N posts only)
define("L_CMD_SIZE", "tam,fonte"); // size (change/reset the size of the font in chat)
define("L_CMD_SORT", "list,ordemlist"); // sort (sort - ascending the usernames in the lists, alphabetically or by the time they joined chat)
define("L_CMD_TIMESTAMP", "tempo"); // timestamp (show/hide the timestamp in posts and server/worldtime in the status bar)
define("L_CMD_TOPIC", "topico"); // topic (set/change the topic)
define("L_CMD_UTUBE", ""); //tube,utube,youtube (posts an youtube video movie in an embedded Flash player)
define("L_CMD_VIDEO", "víd,vídeo,tocar"); //vid,video,play (posts a video movie or an audio source in an embedded Flash player)
define("L_CMD_WISP", "suss,sussurro"); //wisp,whisp (send a whisper / private message to an user in a different room)
define("L_CMD_WHOIS", "queme,sobre"); // whois,about (shows the profile page of an user) 
?>