<?php
// File : bulgarian/localized.cmds.php (23.08.2009 - rev.1)
// Translation by Peter Petrov <peter.m.petrov@gmail.com>
// Do not use ' but use ’ instead (utf-8 edit bug)

// You can use more than one word (synonyms, abbreviations) as commands in your language. Multiple words must be separated by commas, without spaces! You have the original English strings/commands as examples below (no need to add the English words here)
define("L_CMD_ANNOUNCE", "съобщение"); // announce (send a global announcement in all rooms)
define("L_CMD_AWAY", "наблизо"); // away (set as away from pc or back)
define("L_CMD_BAN", "забрани"); // ban (block an user from joining chat)
define("L_CMD_BOT", "бот"); // bot (start/stop the bot in a room)
define("L_CMD_BUZZ", "бръм"); // buzz (play a buzz/sound alert in the room)
define("L_CMD_CLEAR", "изчисти"); // clear (clear the messages frame and show only the last 5 posts)
define("L_CMD_DEMOTE", "понижи"); // demote (demote an user to the lower power level - admin->mod->user)
define("L_CMD_DICE", "зарче"); // dice (throw the dice)
define("L_CMD_HELP", "помощ"); // ?,help (open the help popup page)
define("L_CMD_HIGH", "засвети"); // high (highlight someones posts)
define("L_CMD_IGNORE", "пренебрегни"); // ignore (ignore an user - hide his posts and show the list of ignored people)
define("L_CMD_IMG", "картинка"); // img (post an image in the chat)
define("L_CMD_INVITE", "покани"); // invite (send an invitation to the user to follow you in your room)
define("L_CMD_JOIN", "ела"); // join (join an existing room)
define("L_CMD_KICK", "изритай,изхвърли"); // kick,boot (kick an user from a room)
define("L_CMD_LTR", "л-д,лд,ляво"); // ltr (post a left-to-right text)
define("L_CMD_MATH", "мат,мате"); // math (post MathJax equations in chat)
define("L_CMD_ME", "аз"); // me (tell the room what you are doing)
define("L_CMD_MR", "г-н,г-жа,г-ца,гн,гжа,гца"); // mr (same as "me" but with the gender prefix)
define("L_CMD_MSG", "бележка,до"); // msg,to (send a private message)
define("L_CMD_NOTIFY", "уведоми"); // notify (enable/disable notifications)
define("L_CMD_ORDER", "ред"); // order (change the posts order to first-on-top or first-on-bottom - not available in IE and FF)
define("L_CMD_PROFILE", "профил"); // profile (open the personal profile page for editing)
define("L_CMD_PROMOTE", "повиши"); // promote (promote an user to the next power level - user->mod->admin)
define("L_CMD_QUIT", "напусни,излез"); // quit,bye,exit (quit a room)
define("L_CMD_RECALL", "възстанови"); // !,recall (recalls last sent message in the message box)
define("L_CMD_REFRESH", "презареждане"); // refresh,reload (modify/reset the time between browser refreshes/reloads)
define("L_CMD_ROOM", "стая"); // room (send an announcement/warning to the current room)
define("L_CMD_RTL", "д-л,дл,дясно"); // rtl (post a right-to-left text)
define("L_CMD_SAVE", "запиши,експортирай,изнеси"); // save,export (open the last N posts to be exported)
define("L_CMD_SHOW", "покажи,последни"); // show,last (reset the messages frame to show the last 5 / N posts only)
define("L_CMD_SIZE", "размер"); //size (change/reset the size of the font in chat)
define("L_CMD_SORT", "сорт,сортиране"); // sort (sort - ascending the usernames in the lists, alphabetically or by the time they joined chat)
define("L_CMD_TIMESTAMP", "време"); // timestamp (show/hide the timestamp in posts and server/worldtime in the status bar)
define("L_CMD_TOPIC", "тема"); // topic (set/change the topic)
define("L_CMD_WISP", "пошепни,подшушни"); //wisp,whisp (send a whisper / private message to an user in a different room)
define("L_CMD_WHOIS", "кой,относно"); // whois,about (shows the profile page of an user) 
?>