<?php
// File : french/localized.cmds.php (23.08.2009 - rev.1)
// Translation by Pierre Liget <pierre.liget@free.com>
// Do not use ' but use ’ instead (utf-8 edit bug)

// You can use more than one word (synonyms, abbreviations) as commands in your language. Multiple words must be separated by commas, without spaces! You have the original English strings/commands as examples below (no need to add the English words here)
# Example: define("L_CMD_AWAY", "plec,brb,revin");

define("L_CMD_ANNOUNCE", "annonce"); // announce (send a global announcement in all rooms)
define("L_CMD_AWAY", "absent"); // away (set as away from pc or back)
define("L_CMD_BAN", "bannir"); // ban (block an user from joining chat)
define("L_CMD_BOT", ""); // bot (start/stop the bot in a room)
define("L_CMD_BUZZ", "son"); // buzz (play a buzz/sound alert in the room)
define("L_CMD_CLEAR", "effacer"); // clear (clear the messages frame and show only the last 5 posts)
define("L_CMD_DEMOTE", "retrograde"); // demote (demote an user to the lower power level - admin->mod->user)
define("L_CMD_DICE", "de,dé"); // dice (throw the dice)
define("L_CMD_HELP", "aide"); // ?,help (open the help popup page)
define("L_CMD_HIGH", "surligne"); // high (highlight someone's posts)
define("L_CMD_IGNORE", ""); // ignore (ignore an user - hide his posts and show the list of ignored people)
define("L_CMD_IMG", ""); // img (post an image in the chat)
define("L_CMD_INVITE", ""); // invite (send an invitation to the user to follow you in your room)
define("L_CMD_JOIN", "joindre"); // join (join an existing room)
define("L_CMD_KICK", "ejecter,éjecter"); // kick,boot (kick an user from a room)
define("L_CMD_LTR", "gad,gàd,g2d"); // ltr (post a left-to-right text)
define("L_CMD_ME", "je"); // me (tell the room what you are doing)
define("L_CMD_MR", "moi"); // mr (same as "me" but with the gender prefix)
define("L_CMD_MSG", "priv"); // msg,to (send a private message)
define("L_CMD_NOTIFY", "notif"); // notify (enable/disable notifications)
define("L_CMD_ORDER", "ordre"); // order (change the posts order to first-on-top or first-on-bottom - not available in IE and FF)
define("L_CMD_PROFILE", "profil"); // profile (open the personal profile page for editing)
define("L_CMD_PROMOTE", "prom,promouvoir"); // promote (promote an user to the next power level - user->mod->admin)
define("L_CMD_QUIT", "quitter,adieu,salut"); // quit,bye,exit (quit a room)
define("L_CMD_RECALL", "rappel"); // !,recall (recall last sent message in the message box)
define("L_CMD_REFRESH", "actu,actualiser"); // refresh,reload (modify/reset the time between browser refreshes/reloads)
define("L_CMD_ROOM", "salon"); // room (send an announcement/warning to the current room)
define("L_CMD_RTL", "dag,dàg,d2g"); // rtl (post a right-to-left text)
define("L_CMD_SAVE", ""); // save,export (open the last N posts to be exported)
define("L_CMD_SHOW", "montrer,dernier"); // show,last (reset the messages frame to show the last 5 / N posts only)
define("L_CMD_SIZE", "taille"); // size (change/reset the size of the font in chat)
define("L_CMD_SORT", "tri"); // sort (sort - ascending the usernames in the lists, alphabetically or by the time they joined chat)
define("L_CMD_TIMESTAMP", "horo,horodatage"); // timestamp (show/hide the timestamp in posts and server/worldtime in the status bar)
define("L_CMD_TOPIC", "sujet"); // topic (set/change the topic)
define("L_CMD_WISP", "murm,murmure"); //wisp,whisp (send a whisper / private message to an user in a different room)
define("L_CMD_WHOIS", "qui,apropos"); // whois,about (shows the profile page of an user) 
?>