<?php
// File : hebrew/localized.cmds.php (23.08.2009 - rev.1)
// Original file by Ciprian Murariu <ciprianmp@yahoo.com>
// Hebrew translation by Shula Amokshim <shula.amokshim @gmx.net>
// Do not use ' but use ’ instead (utf-8 edit bug)

// You can use more than one word (synonyms, abbreviations) as commands in your language. Multiple words must be separated by commas, without spaces! You have the original English strings/commands as examples below (no need to add the English words here)
define("L_CMD_ANNOUNCE", "להכריז,להודיע"); // announce (send a global announcement in all rooms)
define("L_CMD_AWAY", ""); // away (set as away from pc or back)
define("L_CMD_BAN", ""); // ban (block an user from joining chat)
define("L_CMD_BOT", ""); // bot (start/stop the bot in a room)
define("L_CMD_BUZZ", "ציפצוף"); // buzz (play a buzz/sound alert in the room)
define("L_CMD_CLEAR", "לנקות"); // clear (clear the messages frame and show only the last 5 posts)
define("L_CMD_DEMOTE", ""); // demote (demote an user to the lower power level - admin->mod->user)
define("L_CMD_DICE", "קוביות"); // dice (throw the dice)
define("L_CMD_HELP", "עזרה"); // ?,help (open the help popup page)
define("L_CMD_HIGH", ""); // high (highlight someones posts)
define("L_CMD_IGNORE", "להתעלם"); // ignore (ignore an user - hide his posts and show the list of ignored people)
define("L_CMD_IMG", ""); // img (post an image in the chat)
define("L_CMD_INVITE", "הזמנה,להזמין"); // invite (send an invitation to the user to follow you in your room)
define("L_CMD_JOIN", "לצרף"); // join (join an existing room)
define("L_CMD_KICK", "לבעוט,בעט,להעיף"); // kick,boot (kick an user from a room)
define("L_CMD_LTR", ""); // ltr (post a left-to-right text)
define("L_CMD_ME", ""); // me (tell the room what you are doing)
define("L_CMD_MR", ""); // mr (same as "me" but with the gender prefix)
define("L_CMD_MSG", "אל,פרטי"); // msg,to (send a private message)
define("L_CMD_NOTIFY", ""); // notify (enable/disable notifications)
define("L_CMD_ORDER", "לסדר"); // order (change the posts order to first-on-top or first-on-bottom - not available in IE and FF)
define("L_CMD_PROFILE", "פרופיל"); // profile (open the personal profile page for editing)
define("L_CMD_PROMOTE", ""); // promote (promote an user to the next power level - user->mod->admin)
define("L_CMD_QUIT", "ביי,סיום,לצאת"); // quit,bye,exit (quit a room)
define("L_CMD_RECALL", ""); // !,recall (recalls last sent message in the message box)
define("L_CMD_REFRESH", "לרענן,רענן"); // refresh,reload (modify/reset the time between browser refreshes/reloads)
define("L_CMD_ROOM", ""); // room (send an announcement/warning to the current room)
define("L_CMD_RTL", ""); // rtl (post a right-to-left text)
define("L_CMD_SAVE", "לשמור,שמור,שמירה"); // save,export (open the last N posts to be exported)
define("L_CMD_SHOW", "הצג,אחרונות,אחרונים"); // show,last (reset the messages frame to show the last 5 / N posts only)
define("L_CMD_SIZE", "גודל"); //size (change/reset the size of the font in chat)
define("L_CMD_SORT", "למיין"); // sort (sort - ascending the usernames in the lists, alphabetically or by the time they joined chat)
define("L_CMD_TIMESTAMP", "זמנים"); // timestamp (show/hide the timestamp in posts and server/worldtime in the status bar)
define("L_CMD_TOPIC", ""); // topic (set/change the topic)
define("L_CMD_WISP", ""); //wisp,whisp (send a whisper / private message to an user in a different room)
define("L_CMD_WHOIS", "אודות,מיזה"); // whois,about (shows the profile page of an user) 
?>